name: Backend Test
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    test:
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies in Root
              run: | 
                cd $GITHUB_WORKSPACE
                npm install
            - name: Source Environment Variables
              run: |
                cd $GITHUB_WORKSPACE
                source .env

            - name: Install Dependencies
              run: | 
                cd $GITHUB_WORKSPACE/ServerSide 
                npm install

            - name: Test
              run: |
                cd $GITHUB_WORKSPACE/ServerSide
                npm run test
              env:
                AWS_REGION: ${{ secrets.AWS_REGION }}

