name: Backend Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.REGION }}

      - name: Install Dependencies in Root
        run: | 
          cd $GITHUB_WORKSPACE
          npm install

      - name: Install Dependencies
        run: | 
          cd $GITHUB_WORKSPACE/ServerSide 
          npm install

      - name: Test
        run: |
          cd $GITHUB_WORKSPACE/ServerSide
          npm run test
        env:
          REGION: ${{secrets.REGION}}
