name: Frontend
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: | 
                cd $GITHUB_WORKSPACE/ClientSide 
                npm install

            - name: Build
              run: |
                cd $GITHUB_WORKSPACE/ClientSide
                npm run build