# name: 'Terraform'

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   terraform:
#     name: 'Terraform'
#     runs-on: ubuntu-latest
#     environment: production

#     defaults:
#       run:
#         shell: bash

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v4

#     - name: List Current Directory Contents
#       run: ls -al

#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#         aws-region: ${{ secrets.REGION }}

#     - name: Terraform Init
#       run: terraform init
    
#     - name: Terraform Format
#       run: terraform fmt -check
    
#     - name: Terraform Plan
#       run: |
#         cd $GITHUB_WORKSPACE/Terraform
#         terraform init
#         terraform plan -input=false

#     - name: Terraform Apply
#       run: |
#         cd $GITHUB_WORKSPACE/Terraform
#         terraform apply -auto-approve -input=false
